#Complementary01.sh
0,StartLogging 
0,LogScriptFileName

#Stage 1 raise left arm - note: two complementary motors- hold angle Y to 0deg and move X to 10deg
1,MotorAngle(MOTOR_LEFT_LOWER_ARM_INSIDE,MOTOR_LEFT_LOWER_ARM_OUTSIDE,3,5000,POT_LEFT_ELBOW_Y,Y,180,-2,2,POT_LEFT_ELBOW_X,X,80,-2,2,WAIT_STAGE|MIN_VELOCITY=5|MAX_VELOCITY=7|MAX_THRUST=3|MAX_REVERSE_THRUST=2|MAX_ACCEL=0.1|ABORT_ON_TIMEOUT|REQUIRED)
#1,MotorAngle(MOTOR_LEFT_LOWER_ARM_INSIDE,MOTOR_LEFT_LOWER_ARM_OUTSIDE,3,5000,POT_LEFT_ELBOW_X,X,100,-2,2,WAIT_STAGE|MIN_VELOCITY=10|MAX_VELOCITY=40|MAX_THRUST=10|MAX_REVERSE_THRUST=5|MAX_ACCEL=5|ABORT_ON_TIMEOUT|FUTURE_LOG|REQUIRED)


5000,StopLogging

