#RightLegLift03.sh
0,StartLogging 
0,LogScriptFileName
#StartTimeInMS,HoldAngleWithMotor(AccelName,AccelAngleXYorZ,TargetAngle,DegreesPlus,DegreesMinus,MotorName,Dir*Strength,Duration/TimeOut,flags)

#legs spread 22cm from left foot to right foot center

#constant thrust step right
#no thrust analysis, but does check for angle


0,StoreAngle(ACCEL_LEFT_LOWER_LEG,Z,LLLZ0)
0,StoreAngle(ACCEL_RIGHT_LOWER_LEG,Z,RLLZ0)
0,StoreAngle(ACCEL_TORSO,Z,TZ0)
0,StoreAngle(ACCEL_TORSO,X,TX0)
0,StoreAngle(ACCEL_RIGHT_UPPER_LEG,X,RULX0)
0,StoreAngle(ACCEL_RIGHT_LOWER_LEG,X,RLLX)
0,StoreAngle(ACCEL_RIGHT_UPPER_LEG,Z,RULZ0)

#Stage 1: LEAN LEFT 
#both ankles lean ankle until LLLZ is 0, thrust=7
#alt: left ankle turns until LLLZ=-1 LLLZ starts at 3, important to limit thrust
1,MotorAccel(MOTOR_LEFT_SIDE,MOTOR_RIGHT_SIDE,3,5000,ACCEL_LEFT_LOWER_LEG,Z,-4,-1,1,WAIT_STAGE|DOUBLE_THRUST|FUTURE_LOG|CONSTANT_THRUST)
#1,MotorAccel(MOTOR_LEFT_SIDE,MOTOR_RIGHT_SIDE,3,5000,ACCEL_LEFT_LOWER_LEG,Z,-4,-1,1,WAIT_STAGE|DOUBLE_THRUST|FUTURE_LOG|CONSTANT_THRUST)
1,MotorAccel(MOTOR_LEFT_ANKLE,3,5000,ACCEL_LEFT_FOOT,Z,0,-1,1,ACCEL_LEFT_LOWER_LEG,Z,-4,-1,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG|MAX_THRUST=3)
1,MotorAccel(MOTOR_RIGHT_ANKLE,3,5000,ACCEL_RIGHT_FOOT,Z,0,-1,1,ACCEL_LEFT_LOWER_LEG,Z,-4,-1,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG|MAX_THRUST=3)

#1,MotorAccel(MOTOR_LEFT_ANKLE,MOTOR_RIGHT_ANKLE,7,5000,ACCEL_LEFT_LOWER_LEG,Z,-4,-1,1,WAIT_STAGE|DOUBLE_THRUST|FUTURE_LOG|CONSTANT_THRUST)

#stage 2: LEFT_SIDE reverses, to make torso Z straighten, and put torso weight over left leg
2,MotorAccel(MOTOR_LEFT_SIDE,3,3000,ACCEL_TORSO,Z,1,-1,1,WAIT_STAGE|MAX_THRUST=6)
#ABORT_ANGLE0=5 - end script if ankle Z turns past 5 degrees
2,MotorAccel(MOTOR_LEFT_ANKLE,3,3000,ACCEL_LEFT_FOOT,Z,0,-10,10,ACCEL_LEFT_LOWER_LEG,Z,-5,-2,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG|MAX_THRUST=9|ABORT_ANGLE0=5)
#2,MotorAccel(MOTOR_RIGHT_ANKLE,3,3000,ACCEL_RIGHT_FOOT,Z,0,-10,10,ACCEL_LEFT_LOWER_LEG,Z,-5,-2,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG|MAX_THRUST=3)

#left foot holds up lower left leg
2,MotorAccel(MOTOR_LEFT_FOOT,3,3000,ACCEL_LEFT_LOWER_LEG,X,CurrentAngle,-1,1,WAIT_STAGE|HOLD_ANGLE|MAX_THRUST=6)
2,MotorAccel(MOTOR_RIGHT_FOOT,3,3000,ACCEL_RIGHT_LOWER_LEG,X,CurrentAngle,-1,1,WAIT_STAGE|HOLD_ANGLE|MAX_THRUST=6)


#2,MotorAccel(MOTOR_LEFT_ANKLE,3,5000,ACCEL_LEFT_FOOT,Z,0,-1,1,ACCEL_LEFT_LOWER_LEG,Z,-4,-1,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG|MAX_THRUST=3)
#2,MotorAccel(MOTOR_RIGHT_SIDE,3,7000,ACCEL_RIGHT_UPPER_LEG,Z,CurrentAngle,-1,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG|MAX_THRUST=6)


#Stage 3: LIFT RIGHT LEG only (no knee or foot movement) 
#(LEFT FOOT MOTOR HOLDS ROBOT FROM FALLING FORWARD)
3,MotorAccel(MOTOR_RIGHT_LEG,10,2000,ACCEL_RIGHT_UPPER_LEG,X,20,-1,1,WAIT_STAGE|CONSTANT_THRUST)
3,MotorAccel(MOTOR_LEFT_LEG,10,2000,ACCEL_RIGHT_UPPER_LEG,X,20,-1,1,WAIT_STAGE|CONSTANT_THRUST|HOLD_ANGLE)
#important that left knee hold ULX to 17 standing is 10 - left knee needs to push hard initially
3,MotorAccel(MOTOR_LEFT_KNEE,10,2000,ACCEL_LEFT_UPPER_LEG,X,CurrentAngle,-0.5,0.5,WAIT_STAGE|HOLD_ANGLE)
#important the left side holds torso Z to 0 (changed to CurrentAngle)
3,MotorAccel(MOTOR_LEFT_SIDE,3,2000,ACCEL_TORSO,Z,0,-1,1,WAIT_STAGE|HOLD_ANGLE|MAX_THRUST=6)
#important that left ankle holds lower leg Z or else robot falls right  setting Z=-4 forces ankle to thrust immediately
#3,MotorAccel(MOTOR_LEFT_ANKLE,10,2000,ACCEL_LEFT_FOOT,Z,0,-5,5,ACCEL_LEFT_LOWER_LEG,Z,-4,-1,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG|MAX_THRUST=12)
3,MotorAccel(MOTOR_LEFT_ANKLE,10,2000,ACCEL_LEFT_LOWER_LEG,Z,-4,-1,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG|MAX_THRUST=12)
#torso motor holds up torso X
#3,MotorAccel(MOTOR_TORSO,9,2000,ACCEL_TORSO,X,CurrentAngle,-1,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG)
#right side pushes away from left leg
3,MotorAccel(MOTOR_RIGHT_SIDE,6,2000,ACCEL_RIGHT_UPPER_LEG,Z,CurrentAngle,-1,1,WAIT_STAGE|HOLD_ANGLE)
#3,MotorAccel(MOTOR_RIGHT_SIDE,6,2000,ACCEL_TORSO,Z,0,-1,1,WAIT_STAGE|HOLD_ANGLE)
#left foot holds lower leg to current angle 
3,MotorAccel(MOTOR_LEFT_FOOT,5,2000,ACCEL_LEFT_FOOT,X,0,-5,5,ACCEL_LEFT_LOWER_LEG,X,CurrentAngle[LLLX],-1,1,WAIT_STAGE|HOLD_ANGLE|FUTURE_LOG)
#left ankle holds robot weight from falling left
#2,MotorAccel(MOTOR_LEFT_ANKLE,10,6100,ACCEL_LEFT_FOOT,Z,0,-5,5,ACCEL_LEFT_LOWER_LEG,Z,CurrentAngle,-1,1,WAIT_STAGE|HOLD_ANGLE|MAX_THRUST=16|FUTURE_LOG|LAST_STAGE=6100)

#right ankle hold Z at 0
3,MotorAccel(MOTOR_RIGHT_ANKLE,10,2000,ACCEL_RIGHT_FOOT,Z,0,-3,3,WAIT_STAGE|FUTURE_LOG|HOLD_ANGLE)

#bend right knee slightly to help get right leg off ground standing RLLX=-5
#3,MotorAccel(MOTOR_RIGHT_KNEE,10,2000,ACCEL_RIGHT_LOWER_LEG,X,-10,-1,1,WAIT_STAGE|FUTURE_LOG|HOLD_ANGLE)
#3,MotorAccel(MOTOR_RIGHT_KNEE,10,2000,ACCEL_RIGHT_LOWER_LEG,X,CurrentAnglePlus,-5,-1,1,WAIT_STAGE|FUTURE_LOG|HOLD_ANGLE)

#right foot bends up to lower friction of foot with ground
#3,MotorAccel(MOTOR_RIGHT_FOOT,6,2000,ACCEL_RIGHT_FOOT,X,8,-0.5,0.5,WAIT_STAGE|FUTURE_LOG|HOLD_ANGLE)


#right foot holds foot parallel to ground X=0 (standing should be x=0, but can be ex: 2)
#3,MotorAccel(MOTOR_RIGHT_FOOT,6,2000,ACCEL_RIGHT_FOOT,X,0,-0.5,0.5,WAIT_STAGE|FUTURE_LOG|HOLD_ANGLE)


#Stage 3: LOWER RIGHT LEG
#3,MotorAccel(MOTOR_RIGHT_LEG,6,400,ACCEL_RIGHT_UPPER_LEG,X,RULX0,-0.5,0.5,WAIT_STAGE|CONSTANT_THRUST)
#3,MotorAccel(MOTOR_RIGHT_KNEE,9,400,ACCEL_RIGHT_LOWER_LEG,X,RLLX,-0.5,0.5,WAIT_STAGE|CONSTANT_THRUST|HOLD_ANGLE)
#3,MotorAccel(MOTOR_RIGHT_FOOT,1,400,ACCEL_RIGHT_FOOT,X,0,-1,1,WAIT_STAGE|HOLD_ANGLE) #does not use constant thrust
#left ankle leans back
#3,MotorAccel(MOTOR_LEFT_ANKLE,10,800,ACCEL_LEFT_FOOT,Z,0,-5,5,ACCEL_LEFT_LOWER_LEG,Z,LLLZ0,-1,1,WAIT_STAGE|HOLD_ANGLE|MAX_THRUST=16|FUTURE_LOG|LAST_STAGE=6100)


#Stage 4: BALANCE
#right ankle needs to lean back too
#4,MotorAccel(MOTOR_RIGHT_ANKLE,10,800,ACCEL_RIGHT_FOOT,Z,0,-5,5,ACCEL_RIGHT_LOWER_LEG,Z,RLLZ0,-1,1,WAIT_STAGE|HOLD_ANGLE|MAX_THRUST=16|LAST_STAGE=6100)
#left and right leg motors kep torso from falling in X
#4,MotorAccel(MOTOR_LEFT_LEG,MOTOR_RIGHT_LEG,4,2000,ACCEL_TORSO,X,TX0,-2,2,WAIT_STAGE|HOLD_ANGLE|DOUBLE_THRUST|FUTURE_LOG)



10000,StopLogging

